/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz
      thread_priority: 98
      cpu_affinity: [4,5]
      lock_memory: true

      joint_impedance_controller:
        type: franka_fr3_arm_controllers/JointImpedanceController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

joint_impedance_controller:
  ros__parameters:
    arm_id: fr3
    k_alpha: 0.3
    deployment_mode: true
    # Lowered slightly from 800 to prevent safety trips at startup
    k_gains:
      - 600.0
      - 600.0
      - 600.0
      - 600.0
      - 250.0
      - 150.0
      - 50.0
    d_gains:
      - 30.0
      - 30.0
      - 30.0
      - 30.0
      - 10.0
      - 10.0
      - 5.0
