lerobot_data_bridge:
  ros__parameters:
    sample_rate_hz: 15.0
    max_data_age_sec: 1.0
    publish_host: "127.0.0.1"
    publish_port: 5555
    task_name: "pick and place"
    deployment_mode: true
    left_robot_ip: "172.16.0.3"
    right_robot_ip: "172.16.0.2"
    deployment_gripper_action_value: 0.0
    include_gripper: true
    include_right_arm: true
    require_gripper_freshness: true
    arm_action_source: "robot_state"

    camera_1_enabled: true
    camera_1_name: "cam_left"
    camera_1_topic: "/cameras/cam_left/image_raw"
    camera_2_enabled: true
    camera_2_name: "cam_front"
    camera_2_topic: "/cameras/cam_front/image_raw"
    camera_3_enabled: true
    camera_3_name: "cam_right"
    camera_3_topic: "/cameras/cam_right/image_raw"
